### ISSUE TITLE
Weighted distance has two different implementations

### ISSUE THREAD

**Issue by ebrahimebrahim** [dmort27/panphon#12]
This not a bug, but an incompatibility between two parts of the code that say "weighted distance".

In `panphon.distance.Distance.weighted_substitution_cost` and `panphon.segment.Segment.weighted_distance`, weighted distance is implemented in almost the same way except that they differ by a factor of 2.

**Comment by dmort27** [comment]
Interesting. I'll look into this when I get the chance, but currently I am squashing much bigger bugs.

**Comment by dmort27** [comment]
Could you look at this again? I can't find `panphon.segment.Segment.weighted_distance` and I'm not sure which piece of code you were referring to.

**Comment by dmort27** [comment]
For complicated reasons, I cannot get rid of either of the functions. I would like to eliminate the one in `distance.py` but, because of the different ways weights are passed to the functions, I cannot just replace it with a call to `weighted_distance`. I have made the two functions mathematically equivalent. I need to think more about how to rationalize the whole structure.
