### ISSUE TITLE
July 11th commit (normalization) leads to exception with certain combined characters

### ISSUE THREAD

**Issue by littell** [dmort27/panphon#16]
The recent change to ipa_segs so that it outputs NFC-normalized strings seems to lead to exceptions in character lookup in the feature edit distances for some combinations (the one we found is e-tilde).  It may be that, after recombining e-tilde into a composed character, it cannot be compared with its reference in ipa_all, which is decomposed.  So probably ipa_all should be run through NFC, or ipa_segs should output NFD-normalized strings, or there should be two ipa_segs for the two different purposes.

**Comment by dmort27** [comment]
Thank you for pointing this out. I am trying to transition to my original vision, which is to use only NFD as an internal representation and to use NFC only as an output representation, but this creates some complications because it is not always clear what is "internal" and what is "external". Probably, ipa_segs should output NFD-normalized strings. When I get a chance, I'll fix this. In the meantime, some solid test cases would be helpful.

**Comment by dmort27** [comment]
I have changed how the normalization works (using NFD only). I have tested the e-tilde case and it seems to work. Please pull, test, and see if it actually does work.

**Comment by erros84** [comment]
Hi David, I was with Patrick at CMU when we found this. Either NFD or NFC **should** work as long as your data and the searche parameters agree. If you're going with NFD, which frankly makes the most sense, you probably need to NFD your CSV data files so you will be comparing apples to apples. 

https://github.com/erros84/panphon/commit/a5b55d38843883cb9a48a7eb51805d3f8b9d4a03

Would you like me to open a pull request?

**Comment by dmort27** [comment]
@MattGyverLee please open a pull request. I thought I did NFD my data files, but apparently this was not the case.

**Comment by dmort27** [comment]
This appears to be fixed.
